spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:IbmIndustrialTraining/ConfigRepository.git
        # uri: git@github.com:IbmIndustrialTraining/{application}.git  
          search-paths: employee

server:
  port: 8002
